camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    generic-properties:
      properties:    
        initialize-telemetry: false
    history-level: audit
      
spring:
  h2:
    console:
      enabled: true